apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vly3e32u7-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:d00ae1caf64ba5c080fcc15a6f4b57e575b5ea94@sha256:81f6d98e7355c7fbb6f65751c3f7c678370d837df049a8eaaddb53e753af1930
          name: container-image
