apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vly3e32u7-nodejs
  janus-idp.io/tekton: vly3e32u7-nodejs
  backstage.io/kubernetes-id: vly3e32u7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vly3e32u7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
