apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vly3e32u7-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vly3e32u7-nodejs 
  name: vly3e32u7-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vly3e32u7-nodejs 
